In [12]:
import numpy as np

# ML Methods

## Gradient Descent

$$\boldsymbol{w}^{(t+1)}=\boldsymbol{w}^{(t)}- \gamma \nabla \mathcal{L}(\boldsymbol{w})$$

## Logistic Regression

Likelihood for logistic regression: $\mathcal{L}(\boldsymbol{w})=\prod_{n=1}^N \pi_{n}^{y_n} (1-\pi_{n})^{1-y_n}$, where $\pi_n(\boldsymbol{x_n})=\frac{e^{\boldsymbol{x_n}^T\boldsymbol{w}}}{1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}} $
Log-likelihood: $l(\boldsymbol{w})=\sum_{n=1}^N(y_n\boldsymbol{x_n}^T\boldsymbol{w}-log(1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}))$

Log-likelihood is differenetiable and concave, all local maxima are global maxima. Use gradient descent or SGD to optimize.

Gradient: $\nabla l(\boldsymbol{w})=[\frac{\partial l}{\partial w_1},\dots, \frac{\partial l}{\partial w_D}]^T =
[\sum_{n=1}^N(y_n-\frac{e^{\boldsymbol{x_n}^T\boldsymbol{w}}}{1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}})x_{n1},\dots,\sum_{n=1}^N(y_n-\frac{e^{\boldsymbol{x_n}^T\boldsymbol{w}}}{1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}})x_{nD}]^T=
\sum_{n=1}^N(y_n-\frac{e^{\boldsymbol{x_n}^T\boldsymbol{w}}}{1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}})\boldsymbol{x_{n}}^T$

Maximize the previous quantity is equivalent to use the following gradient via GD SGD
$\sum_{n=1}^N(\frac{e^{\boldsymbol{x_n}^T\boldsymbol{w}}}{1+e^{\boldsymbol{x_n}^T\boldsymbol{w}}}-y_n)\boldsymbol{x_{n}}^T=\sum_{n=1}^N(\sigma({\boldsymbol{x_n}^T\boldsymbol{w}})-y_n)\boldsymbol{x_{n}}^T$

In [152]:
def sigmoid(x):
    x= pow(x,2.718281828459045)/(1+pow(x,2.718281828459045)) 
    return x

In [153]:
def partial_deriv_w(y, X, w, i):
    S=0
    for n in range(X.shape[0]):
        S+=(sigmoid(np.dot(X[n,:],w))-y[n])*X[n,i]
    return S

In [149]:
def compute_gradient(y, X, w):
    D=w.shape[0]
    L=np.zeros(D)
    for n in range(D):
        L+=(sigmoid(np.dot(X[n,:],w))-y[n])*X[n,:]
    return L

In [155]:
def gradient(y, X, w):
    D=w.shape[0]
    L=np.zeros(D)
    for i in range(D):
        L[i]=partial_deriv_w(y,X,w,i)
    return L

In [180]:
def gradient_descent(y, X, w0, gamma, max_iters):
    w=w0
    for n in range(max_iters):
        grad = gradient(y,X,w)
        #print(grad)
        w = w - gamma*grad
        print(w)
    return w

#y=np.array([1,0,1])
#X=np.array([[9,0,11],[1,0,1],[1,0,1]])
#w0=np.array([-1,1,1])
y=np.array([1,0,1,7])
X=np.array([[9,0,11],[1,0,1],[1,0,1],[1,2,3]])
w0=np.array([0,0,1000])
max_iters=10000
gamma=0.1
gradient_descent(y, X, w0, gamma, max_iters)

[5.00000001e-01 1.20000000e+00 1.00170000e+03]
[1.0000e+00 2.4000e+00 1.0034e+03]
[   1.5    3.6 1005.1]
[   2.00000001    4.8        1006.80000001]
[   2.50000001    6.         1008.50000001]
[   3.00000001    7.2        1010.20000001]
[   3.50000001    8.4        1011.90000001]
[   4.00000001    9.6        1013.60000001]
[   4.50000001   10.8        1015.30000001]
[   5.00000001   12.         1017.00000001]
[   5.50000002   13.2        1018.70000002]
[   6.00000002   14.4        1020.40000002]
[   6.50000002   15.6        1022.10000002]
[   7.00000002   16.8        1023.80000002]
[   7.50000002   18.         1025.50000002]
[   8.00000002   19.2        1027.20000002]
[   8.50000002   20.4        1028.90000002]
[   9.00000002   21.6        1030.60000003]
[   9.50000003   22.8        1032.30000003]
[  10.00000003   24.         1034.00000003]
[  10.50000003   25.2        1035.70000003]
[  11.00000003   26.4        1037.40000003]
[  11.50000003   27.6        1039.10000003]
[  12.00000003 

[ 202.50000025  486.00000001 1688.50000027]
[ 203.00000025  487.20000001 1690.20000027]
[ 203.50000025  488.40000001 1691.90000027]
[ 204.00000026  489.60000001 1693.60000027]
[ 204.50000026  490.80000001 1695.30000027]
[ 205.00000026  492.00000001 1697.00000027]
[ 205.50000026  493.20000001 1698.70000027]
[ 206.00000026  494.40000001 1700.40000027]
[ 206.50000026  495.60000001 1702.10000027]
[ 207.00000026  496.80000001 1703.80000027]
[ 207.50000026  498.00000001 1705.50000027]
[ 208.00000026  499.20000001 1707.20000027]
[ 208.50000026  500.40000001 1708.90000027]
[ 209.00000026  501.60000001 1710.60000027]
[ 209.50000026  502.80000001 1712.30000027]
[ 210.00000026  504.00000001 1714.00000027]
[ 210.50000026  505.20000001 1715.70000027]
[ 211.00000026  506.40000001 1717.40000027]
[ 211.50000026  507.60000001 1719.10000027]
[ 212.00000026  508.80000001 1720.80000027]
[ 212.50000026  510.00000001 1722.50000027]
[ 213.00000026  511.20000001 1724.20000027]
[ 213.50000026  512.40000001 172

[ 401.50000032  963.60000001 2365.10000033]
[ 402.00000032  964.80000001 2366.80000033]
[ 402.50000032  966.00000001 2368.50000033]
[ 403.00000032  967.20000001 2370.20000033]
[ 403.50000032  968.40000001 2371.90000033]
[ 404.00000032  969.60000001 2373.60000033]
[ 404.50000032  970.80000001 2375.30000033]
[ 405.00000032  972.00000001 2377.00000033]
[ 405.50000032  973.20000001 2378.70000033]
[ 406.00000032  974.40000001 2380.40000033]
[ 406.50000032  975.60000001 2382.10000033]
[ 407.00000032  976.80000001 2383.80000033]
[ 407.50000032  978.00000001 2385.50000033]
[ 408.00000032  979.20000001 2387.20000033]
[ 408.50000032  980.40000001 2388.90000033]
[ 409.00000032  981.60000001 2390.60000033]
[ 409.50000032  982.80000001 2392.30000033]
[ 410.00000032  984.00000001 2394.00000033]
[ 410.50000032  985.20000001 2395.70000033]
[ 411.00000032  986.40000001 2397.40000033]
[ 411.50000032  987.60000001 2399.10000033]
[ 412.00000032  988.80000001 2400.80000033]
[ 412.50000032  990.00000001 240

[ 590.00000034 1416.00000001 3006.00000035]
[ 590.50000034 1417.20000001 3007.70000035]
[ 591.00000034 1418.40000001 3009.40000035]
[ 591.50000034 1419.60000001 3011.10000035]
[ 592.00000034 1420.80000001 3012.80000035]
[ 592.50000034 1422.00000001 3014.50000035]
[ 593.00000034 1423.20000001 3016.20000035]
[ 593.50000034 1424.40000001 3017.90000035]
[ 594.00000034 1425.60000001 3019.60000035]
[ 594.50000034 1426.80000001 3021.30000035]
[ 595.00000034 1428.00000001 3023.00000035]
[ 595.50000034 1429.20000001 3024.70000035]
[ 596.00000034 1430.40000001 3026.40000035]
[ 596.50000034 1431.60000001 3028.10000035]
[ 597.00000034 1432.80000001 3029.80000035]
[ 597.50000034 1434.00000001 3031.50000035]
[ 598.00000034 1435.20000001 3033.20000035]
[ 598.50000034 1436.40000001 3034.90000035]
[ 599.00000034 1437.60000001 3036.60000035]
[ 599.50000034 1438.80000001 3038.30000035]
[ 600.00000034 1440.00000001 3040.00000035]
[ 600.50000034 1441.20000001 3041.70000035]
[ 601.00000034 1442.40000001 304

[ 740.00000035 1776.00000001 3516.00000036]
[ 740.50000035 1777.20000001 3517.70000036]
[ 741.00000035 1778.40000001 3519.40000036]
[ 741.50000035 1779.60000001 3521.10000036]
[ 742.00000035 1780.80000001 3522.80000037]
[ 742.50000035 1782.00000001 3524.50000037]
[ 743.00000035 1783.20000001 3526.20000037]
[ 743.50000035 1784.40000001 3527.90000037]
[ 744.00000035 1785.60000001 3529.60000037]
[ 744.50000035 1786.80000001 3531.30000037]
[ 745.00000035 1788.00000001 3533.00000037]
[ 745.50000035 1789.20000001 3534.70000037]
[ 746.00000035 1790.40000001 3536.40000037]
[ 746.50000035 1791.60000001 3538.10000037]
[ 747.00000035 1792.80000001 3539.80000037]
[ 747.50000035 1794.00000001 3541.50000037]
[ 748.00000035 1795.20000001 3543.20000037]
[ 748.50000035 1796.40000001 3544.90000037]
[ 749.00000035 1797.60000001 3546.60000037]
[ 749.50000035 1798.80000001 3548.30000037]
[ 750.00000035 1800.00000001 3550.00000037]
[ 750.50000035 1801.20000001 3551.70000037]
[ 751.00000035 1802.40000001 355

[ 872.50000036 2094.00000001 3966.50000037]
[ 873.00000036 2095.20000001 3968.20000037]
[ 873.50000036 2096.40000001 3969.90000037]
[ 874.00000036 2097.60000001 3971.60000037]
[ 874.50000036 2098.80000001 3973.30000037]
[ 875.00000036 2100.00000001 3975.00000037]
[ 875.50000036 2101.20000001 3976.70000037]
[ 876.00000036 2102.40000001 3978.40000037]
[ 876.50000036 2103.60000001 3980.10000037]
[ 877.00000036 2104.80000001 3981.80000037]
[ 877.50000036 2106.00000001 3983.50000037]
[ 878.00000036 2107.20000001 3985.20000037]
[ 878.50000036 2108.40000001 3986.90000037]
[ 879.00000036 2109.60000001 3988.60000037]
[ 879.50000036 2110.80000001 3990.30000037]
[ 880.00000036 2112.00000001 3992.00000037]
[ 880.50000036 2113.20000001 3993.70000037]
[ 881.00000036 2114.40000001 3995.40000037]
[ 881.50000036 2115.60000001 3997.10000037]
[ 882.00000036 2116.80000001 3998.80000037]
[ 882.50000036 2118.00000001 4000.50000037]
[ 883.00000036 2119.20000001 4002.20000037]
[ 883.50000036 2120.40000001 400

[ 966.00000036 2318.40000001 4284.40000037]
[ 966.50000036 2319.60000001 4286.10000037]
[ 967.00000036 2320.80000001 4287.80000037]
[ 967.50000036 2322.00000001 4289.50000037]
[ 968.00000036 2323.20000001 4291.20000037]
[ 968.50000036 2324.40000001 4292.90000037]
[ 969.00000036 2325.60000001 4294.60000037]
[ 969.50000036 2326.80000001 4296.30000037]
[ 970.00000036 2328.00000001 4298.00000037]
[ 970.50000036 2329.20000001 4299.70000037]
[ 971.00000036 2330.40000001 4301.40000037]
[ 971.50000036 2331.60000001 4303.10000037]
[ 972.00000036 2332.80000001 4304.80000037]
[ 972.50000036 2334.00000001 4306.50000037]
[ 973.00000036 2335.20000001 4308.20000037]
[ 973.50000036 2336.40000001 4309.90000038]
[ 974.00000036 2337.60000001 4311.60000038]
[ 974.50000036 2338.80000001 4313.30000038]
[ 975.00000036 2340.00000001 4315.00000038]
[ 975.50000036 2341.20000001 4316.70000038]
[ 976.00000036 2342.40000001 4318.40000038]
[ 976.50000036 2343.60000001 4320.10000038]
[ 977.00000036 2344.80000001 432

[1071.00000036 2570.40000001 4641.40000038]
[1071.50000036 2571.60000001 4643.10000038]
[1072.00000036 2572.80000001 4644.80000038]
[1072.50000036 2574.00000001 4646.50000038]
[1073.00000036 2575.20000001 4648.20000038]
[1073.50000036 2576.40000001 4649.90000038]
[1074.00000036 2577.60000001 4651.60000038]
[1074.50000036 2578.80000001 4653.30000038]
[1075.00000036 2580.00000001 4655.00000038]
[1075.50000036 2581.20000001 4656.70000038]
[1076.00000036 2582.40000001 4658.40000038]
[1076.50000036 2583.60000001 4660.10000038]
[1077.00000036 2584.80000001 4661.80000038]
[1077.50000036 2586.00000001 4663.50000038]
[1078.00000036 2587.20000001 4665.20000038]
[1078.50000036 2588.40000001 4666.90000038]
[1079.00000036 2589.60000001 4668.60000038]
[1079.50000036 2590.80000001 4670.30000038]
[1080.00000036 2592.00000001 4672.00000038]
[1080.50000036 2593.20000001 4673.70000038]
[1081.00000036 2594.40000001 4675.40000038]
[1081.50000036 2595.60000001 4677.10000038]
[1082.00000036 2596.80000001 467

[1177.50000036 2826.00000001 5003.50000038]
[1178.00000036 2827.20000001 5005.20000038]
[1178.50000036 2828.40000001 5006.90000038]
[1179.00000036 2829.60000001 5008.60000038]
[1179.50000036 2830.80000001 5010.30000038]
[1180.00000036 2832.00000001 5012.00000038]
[1180.50000036 2833.20000001 5013.70000038]
[1181.00000036 2834.40000001 5015.40000038]
[1181.50000036 2835.60000001 5017.10000038]
[1182.00000036 2836.80000001 5018.80000038]
[1182.50000036 2838.00000001 5020.50000038]
[1183.00000036 2839.20000001 5022.20000038]
[1183.50000036 2840.40000001 5023.90000038]
[1184.00000036 2841.60000001 5025.60000038]
[1184.50000036 2842.80000001 5027.30000038]
[1185.00000036 2844.00000001 5029.00000038]
[1185.50000036 2845.20000001 5030.70000038]
[1186.00000036 2846.40000001 5032.40000038]
[1186.50000037 2847.60000001 5034.10000038]
[1187.00000037 2848.80000001 5035.80000038]
[1187.50000037 2850.00000001 5037.50000038]
[1188.00000037 2851.20000001 5039.20000038]
[1188.50000037 2852.40000001 504

[1280.50000037 3073.20000001 5353.70000038]
[1281.00000037 3074.40000001 5355.40000038]
[1281.50000037 3075.60000001 5357.10000038]
[1282.00000037 3076.80000001 5358.80000038]
[1282.50000037 3078.00000001 5360.50000038]
[1283.00000037 3079.20000001 5362.20000038]
[1283.50000037 3080.40000001 5363.90000038]
[1284.00000037 3081.60000001 5365.60000038]
[1284.50000037 3082.80000001 5367.30000038]
[1285.00000037 3084.00000001 5369.00000038]
[1285.50000037 3085.20000001 5370.70000038]
[1286.00000037 3086.40000001 5372.40000038]
[1286.50000037 3087.60000001 5374.10000038]
[1287.00000037 3088.80000001 5375.80000038]
[1287.50000037 3090.00000001 5377.50000038]
[1288.00000037 3091.20000001 5379.20000038]
[1288.50000037 3092.40000001 5380.90000038]
[1289.00000037 3093.60000001 5382.60000038]
[1289.50000037 3094.80000001 5384.30000038]
[1290.00000037 3096.00000001 5386.00000038]
[1290.50000037 3097.20000001 5387.70000038]
[1291.00000037 3098.40000001 5389.40000038]
[1291.50000037 3099.60000001 539

[1395.50000037 3349.20000002 5744.70000038]
[1396.00000037 3350.40000002 5746.40000038]
[1396.50000037 3351.60000002 5748.10000038]
[1397.00000037 3352.80000002 5749.80000038]
[1397.50000037 3354.00000002 5751.50000038]
[1398.00000037 3355.20000002 5753.20000038]
[1398.50000037 3356.40000002 5754.90000038]
[1399.00000037 3357.60000002 5756.60000038]
[1399.50000037 3358.80000002 5758.30000038]
[1400.00000037 3360.00000002 5760.00000038]
[1400.50000037 3361.20000002 5761.70000038]
[1401.00000037 3362.40000002 5763.40000038]
[1401.50000037 3363.60000002 5765.10000038]
[1402.00000037 3364.80000002 5766.80000038]
[1402.50000037 3366.00000002 5768.50000038]
[1403.00000037 3367.20000002 5770.20000038]
[1403.50000037 3368.40000002 5771.90000038]
[1404.00000037 3369.60000002 5773.60000038]
[1404.50000037 3370.80000002 5775.30000038]
[1405.00000037 3372.00000002 5777.00000038]
[1405.50000037 3373.20000002 5778.70000038]
[1406.00000037 3374.40000002 5780.40000038]
[1406.50000037 3375.60000002 578

[1510.00000037 3624.00000002 6134.00000039]
[1510.50000037 3625.20000002 6135.70000039]
[1511.00000037 3626.40000002 6137.40000039]
[1511.50000037 3627.60000002 6139.10000039]
[1512.00000037 3628.80000002 6140.80000039]
[1512.50000037 3630.00000002 6142.50000039]
[1513.00000037 3631.20000002 6144.20000039]
[1513.50000037 3632.40000002 6145.90000039]
[1514.00000037 3633.60000002 6147.60000039]
[1514.50000037 3634.80000002 6149.30000039]
[1515.00000037 3636.00000002 6151.00000039]
[1515.50000037 3637.20000002 6152.70000039]
[1516.00000037 3638.40000002 6154.40000039]
[1516.50000037 3639.60000002 6156.10000039]
[1517.00000037 3640.80000002 6157.80000039]
[1517.50000037 3642.00000002 6159.50000039]
[1518.00000037 3643.20000002 6161.20000039]
[1518.50000037 3644.40000002 6162.90000039]
[1519.00000037 3645.60000002 6164.60000039]
[1519.50000037 3646.80000002 6166.30000039]
[1520.00000037 3648.00000002 6168.00000039]
[1520.50000037 3649.20000002 6169.70000039]
[1521.00000037 3650.40000002 617

[1632.00000037 3916.80000002 6548.80000039]
[1632.50000037 3918.00000002 6550.50000039]
[1633.00000037 3919.20000002 6552.20000039]
[1633.50000037 3920.40000002 6553.90000039]
[1634.00000037 3921.60000002 6555.60000039]
[1634.50000037 3922.80000002 6557.30000039]
[1635.00000037 3924.00000002 6559.00000039]
[1635.50000037 3925.20000002 6560.70000039]
[1636.00000037 3926.40000002 6562.40000039]
[1636.50000037 3927.60000002 6564.10000039]
[1637.00000037 3928.80000002 6565.80000039]
[1637.50000037 3930.00000002 6567.50000039]
[1638.00000037 3931.20000002 6569.20000039]
[1638.50000037 3932.40000002 6570.90000039]
[1639.00000037 3933.60000002 6572.60000039]
[1639.50000037 3934.80000002 6574.30000039]
[1640.00000037 3936.00000002 6576.00000039]
[1640.50000037 3937.20000002 6577.70000039]
[1641.00000037 3938.40000002 6579.40000039]
[1641.50000037 3939.60000002 6581.10000039]
[1642.00000037 3940.80000002 6582.80000039]
[1642.50000037 3942.00000002 6584.50000039]
[1643.00000037 3943.20000002 658

[1734.50000037 4162.80000002 6897.30000039]
[1735.00000037 4164.00000002 6899.00000039]
[1735.50000037 4165.20000002 6900.70000039]
[1736.00000037 4166.40000002 6902.40000039]
[1736.50000037 4167.60000002 6904.10000039]
[1737.00000037 4168.80000002 6905.80000039]
[1737.50000037 4170.00000002 6907.50000039]
[1738.00000037 4171.20000002 6909.20000039]
[1738.50000037 4172.40000002 6910.90000039]
[1739.00000037 4173.60000002 6912.60000039]
[1739.50000037 4174.80000002 6914.30000039]
[1740.00000037 4176.00000002 6916.00000039]
[1740.50000037 4177.20000002 6917.70000039]
[1741.00000037 4178.40000002 6919.40000039]
[1741.50000037 4179.60000002 6921.10000039]
[1742.00000037 4180.80000002 6922.80000039]
[1742.50000037 4182.00000002 6924.50000039]
[1743.00000037 4183.20000002 6926.20000039]
[1743.50000037 4184.40000002 6927.90000039]
[1744.00000037 4185.60000002 6929.60000039]
[1744.50000037 4186.80000002 6931.30000039]
[1745.00000037 4188.00000002 6933.00000039]
[1745.50000037 4189.20000002 693

[1840.00000037 4416.00000002 7256.00000039]
[1840.50000037 4417.20000002 7257.70000039]
[1841.00000037 4418.40000002 7259.40000039]
[1841.50000037 4419.60000002 7261.10000039]
[1842.00000037 4420.80000002 7262.80000039]
[1842.50000037 4422.00000002 7264.50000039]
[1843.00000037 4423.20000002 7266.20000039]
[1843.50000037 4424.40000002 7267.90000039]
[1844.00000037 4425.60000002 7269.60000039]
[1844.50000037 4426.80000002 7271.30000039]
[1845.00000037 4428.00000002 7273.00000039]
[1845.50000037 4429.20000002 7274.70000039]
[1846.00000037 4430.40000002 7276.40000039]
[1846.50000037 4431.60000002 7278.10000039]
[1847.00000037 4432.80000002 7279.80000039]
[1847.50000037 4434.00000002 7281.50000039]
[1848.00000037 4435.20000002 7283.20000039]
[1848.50000037 4436.40000002 7284.90000039]
[1849.00000037 4437.60000002 7286.60000039]
[1849.50000037 4438.80000002 7288.30000039]
[1850.00000037 4440.00000002 7290.00000039]
[1850.50000037 4441.20000002 7291.70000039]
[1851.00000037 4442.40000002 729

[1962.50000037 4710.00000002 7672.50000039]
[1963.00000037 4711.20000002 7674.20000039]
[1963.50000037 4712.40000002 7675.90000039]
[1964.00000037 4713.60000002 7677.60000039]
[1964.50000037 4714.80000002 7679.30000039]
[1965.00000037 4716.00000002 7681.00000039]
[1965.50000037 4717.20000002 7682.70000039]
[1966.00000037 4718.40000002 7684.40000039]
[1966.50000037 4719.60000002 7686.10000039]
[1967.00000037 4720.80000002 7687.80000039]
[1967.50000037 4722.00000002 7689.50000039]
[1968.00000037 4723.20000002 7691.20000039]
[1968.50000037 4724.40000002 7692.90000039]
[1969.00000037 4725.60000002 7694.60000039]
[1969.50000037 4726.80000002 7696.30000039]
[1970.00000037 4728.00000002 7698.00000039]
[1970.50000037 4729.20000002 7699.70000039]
[1971.00000037 4730.40000002 7701.40000039]
[1971.50000037 4731.60000002 7703.10000039]
[1972.00000037 4732.80000002 7704.80000039]
[1972.50000037 4734.00000002 7706.50000039]
[1973.00000037 4735.20000002 7708.20000039]
[1973.50000037 4736.40000002 770

[2069.00000037 4965.60000002 8034.60000039]
[2069.50000037 4966.80000002 8036.30000039]
[2070.00000037 4968.00000002 8038.00000039]
[2070.50000037 4969.20000002 8039.70000039]
[2071.00000037 4970.40000002 8041.40000039]
[2071.50000037 4971.60000002 8043.10000039]
[2072.00000037 4972.80000002 8044.80000039]
[2072.50000037 4974.00000002 8046.50000039]
[2073.00000037 4975.20000002 8048.20000039]
[2073.50000037 4976.40000002 8049.90000039]
[2074.00000037 4977.60000002 8051.60000039]
[2074.50000037 4978.80000002 8053.30000039]
[2075.00000037 4980.00000002 8055.00000039]
[2075.50000037 4981.20000002 8056.70000039]
[2076.00000037 4982.40000002 8058.40000039]
[2076.50000037 4983.60000002 8060.10000039]
[2077.00000037 4984.80000002 8061.80000039]
[2077.50000037 4986.00000002 8063.50000039]
[2078.00000037 4987.20000002 8065.20000039]
[2078.50000037 4988.40000002 8066.90000039]
[2079.00000037 4989.60000002 8068.60000039]
[2079.50000037 4990.80000002 8070.30000039]
[2080.00000037 4992.00000002 807

[2228.50000038 5348.40000002 8576.90000039]
[2229.00000038 5349.60000002 8578.60000039]
[2229.50000038 5350.80000002 8580.30000039]
[2230.00000038 5352.00000002 8582.00000039]
[2230.50000038 5353.20000002 8583.70000039]
[2231.00000038 5354.40000002 8585.40000039]
[2231.50000038 5355.60000002 8587.10000039]
[2232.00000038 5356.80000002 8588.80000039]
[2232.50000038 5358.00000002 8590.50000039]
[2233.00000038 5359.20000002 8592.20000039]
[2233.50000038 5360.40000002 8593.90000039]
[2234.00000038 5361.60000002 8595.60000039]
[2234.50000038 5362.80000002 8597.30000039]
[2235.00000038 5364.00000002 8599.00000039]
[2235.50000038 5365.20000002 8600.70000039]
[2236.00000038 5366.40000002 8602.40000039]
[2236.50000038 5367.60000002 8604.10000039]
[2237.00000038 5368.80000002 8605.80000039]
[2237.50000038 5370.00000002 8607.50000039]
[2238.00000038 5371.20000002 8609.20000039]
[2238.50000038 5372.40000002 8610.90000039]
[2239.00000038 5373.60000002 8612.60000039]
[2239.50000038 5374.80000002 861

[2375.00000038 5700.00000001 9075.00000039]
[2375.50000038 5701.20000001 9076.70000039]
[2376.00000038 5702.40000001 9078.40000039]
[2376.50000038 5703.60000001 9080.10000039]
[2377.00000038 5704.80000001 9081.80000039]
[2377.50000038 5706.00000001 9083.50000039]
[2378.00000038 5707.20000001 9085.20000039]
[2378.50000038 5708.40000001 9086.90000039]
[2379.00000038 5709.60000001 9088.60000039]
[2379.50000038 5710.80000001 9090.30000039]
[2380.00000038 5712.00000001 9092.00000039]
[2380.50000038 5713.20000001 9093.70000039]
[2381.00000038 5714.40000001 9095.40000039]
[2381.50000038 5715.60000001 9097.10000039]
[2382.00000038 5716.80000001 9098.80000039]
[2382.50000038 5718.00000001 9100.50000039]
[2383.00000038 5719.20000001 9102.20000039]
[2383.50000038 5720.40000001 9103.90000039]
[2384.00000038 5721.60000001 9105.60000039]
[2384.50000038 5722.80000001 9107.30000039]
[2385.00000038 5724.00000001 9109.00000039]
[2385.50000038 5725.20000001 9110.70000039]
[2386.00000038 5726.40000001 911

[2532.00000038 6076.80000001 9608.80000039]
[2532.50000038 6078.00000001 9610.50000039]
[2533.00000038 6079.20000001 9612.20000039]
[2533.50000038 6080.40000001 9613.90000039]
[2534.00000038 6081.60000001 9615.60000039]
[2534.50000038 6082.80000001 9617.30000039]
[2535.00000038 6084.00000001 9619.00000039]
[2535.50000038 6085.20000001 9620.70000039]
[2536.00000038 6086.40000001 9622.40000039]
[2536.50000038 6087.60000001 9624.10000039]
[2537.00000038 6088.80000001 9625.80000039]
[2537.50000038 6090.00000001 9627.50000039]
[2538.00000038 6091.20000001 9629.20000039]
[2538.50000038 6092.40000001 9630.90000039]
[2539.00000038 6093.60000001 9632.60000039]
[2539.50000038 6094.80000001 9634.30000039]
[2540.00000038 6096.00000001 9636.00000039]
[2540.50000038 6097.20000001 9637.70000039]
[2541.00000038 6098.40000001 9639.40000039]
[2541.50000038 6099.60000001 9641.10000039]
[2542.00000038 6100.80000001 9642.80000039]
[2542.50000038 6102.00000001 9644.50000039]
[2543.00000038 6103.20000001 964

[ 2703.50000038  6488.40000001 10191.90000039]
[ 2704.00000038  6489.60000001 10193.60000039]
[ 2704.50000038  6490.80000001 10195.30000039]
[ 2705.00000038  6492.00000001 10197.00000039]
[ 2705.50000038  6493.20000001 10198.70000039]
[ 2706.00000038  6494.40000001 10200.40000039]
[ 2706.50000038  6495.60000001 10202.10000039]
[ 2707.00000038  6496.80000001 10203.80000039]
[ 2707.50000038  6498.00000001 10205.50000039]
[ 2708.00000038  6499.20000001 10207.20000039]
[ 2708.50000038  6500.40000001 10208.90000039]
[ 2709.00000038  6501.60000001 10210.60000039]
[ 2709.50000038  6502.80000001 10212.30000039]
[ 2710.00000038  6504.00000001 10214.00000039]
[ 2710.50000038  6505.20000001 10215.70000039]
[ 2711.00000038  6506.40000001 10217.40000039]
[ 2711.50000038  6507.60000001 10219.10000039]
[ 2712.00000038  6508.80000001 10220.80000039]
[ 2712.50000038  6510.00000001 10222.50000039]
[ 2713.00000038  6511.20000001 10224.20000039]
[ 2713.50000038  6512.40000001 10225.90000039]
[ 2714.000000

[ 2834.50000038  6802.80000001 10637.30000039]
[ 2835.00000038  6804.00000001 10639.00000039]
[ 2835.50000038  6805.20000001 10640.70000039]
[ 2836.00000038  6806.40000001 10642.40000039]
[ 2836.50000038  6807.60000001 10644.10000039]
[ 2837.00000038  6808.80000001 10645.80000039]
[ 2837.50000038  6810.00000001 10647.50000039]
[ 2838.00000038  6811.20000001 10649.20000039]
[ 2838.50000038  6812.40000001 10650.90000039]
[ 2839.00000038  6813.60000001 10652.60000039]
[ 2839.50000038  6814.80000001 10654.30000039]
[ 2840.00000038  6816.00000001 10656.00000039]
[ 2840.50000038  6817.20000001 10657.70000039]
[ 2841.00000038  6818.40000001 10659.40000039]
[ 2841.50000038  6819.60000001 10661.10000039]
[ 2842.00000038  6820.80000001 10662.80000039]
[ 2842.50000038  6822.00000001 10664.50000039]
[ 2843.00000038  6823.20000001 10666.20000039]
[ 2843.50000038  6824.40000001 10667.90000039]
[ 2844.00000038  6825.60000001 10669.60000039]
[ 2844.50000038  6826.80000001 10671.30000039]
[ 2845.000000

[ 3001.50000038  7203.60000001 11205.10000039]
[ 3002.00000038  7204.80000001 11206.80000039]
[ 3002.50000038  7206.00000001 11208.50000039]
[ 3003.00000038  7207.20000001 11210.20000039]
[ 3003.50000038  7208.40000001 11211.90000039]
[ 3004.00000038  7209.60000001 11213.60000039]
[ 3004.50000038  7210.80000001 11215.30000039]
[ 3005.00000038  7212.00000001 11217.00000039]
[ 3005.50000038  7213.20000001 11218.70000039]
[ 3006.00000038  7214.40000001 11220.40000039]
[ 3006.50000038  7215.60000001 11222.10000039]
[ 3007.00000038  7216.80000001 11223.80000039]
[ 3007.50000038  7218.00000001 11225.50000039]
[ 3008.00000038  7219.20000001 11227.20000039]
[ 3008.50000038  7220.40000001 11228.90000039]
[ 3009.00000038  7221.60000001 11230.60000039]
[ 3009.50000038  7222.80000001 11232.30000039]
[ 3010.00000038  7224.00000001 11234.00000039]
[ 3010.50000038  7225.20000001 11235.70000039]
[ 3011.00000038  7226.40000001 11237.40000039]
[ 3011.50000038  7227.60000001 11239.10000039]
[ 3012.000000

[ 3183.00000038  7639.20000001 11822.20000039]
[ 3183.50000038  7640.40000001 11823.90000039]
[ 3184.00000038  7641.60000001 11825.60000039]
[ 3184.50000038  7642.80000001 11827.30000039]
[ 3185.00000038  7644.00000001 11829.00000039]
[ 3185.50000038  7645.20000001 11830.70000039]
[ 3186.00000038  7646.40000001 11832.40000039]
[ 3186.50000038  7647.60000001 11834.10000039]
[ 3187.00000038  7648.80000001 11835.80000039]
[ 3187.50000038  7650.00000001 11837.50000039]
[ 3188.00000038  7651.20000001 11839.20000039]
[ 3188.50000038  7652.40000001 11840.90000039]
[ 3189.00000038  7653.60000001 11842.60000039]
[ 3189.50000038  7654.80000001 11844.30000039]
[ 3190.00000038  7656.00000001 11846.00000039]
[ 3190.50000038  7657.20000001 11847.70000039]
[ 3191.00000038  7658.40000001 11849.40000039]
[ 3191.50000038  7659.60000001 11851.10000039]
[ 3192.00000038  7660.80000001 11852.80000039]
[ 3192.50000038  7662.00000001 11854.50000039]
[ 3193.00000038  7663.20000001 11856.20000039]
[ 3193.500000

[ 3337.00000038  8008.80000001 12345.80000039]
[ 3337.50000038  8010.00000001 12347.50000039]
[ 3338.00000038  8011.20000001 12349.20000039]
[ 3338.50000038  8012.40000001 12350.90000039]
[ 3339.00000038  8013.60000001 12352.60000039]
[ 3339.50000038  8014.80000001 12354.30000039]
[ 3340.00000038  8016.00000001 12356.00000039]
[ 3340.50000038  8017.20000001 12357.70000039]
[ 3341.00000038  8018.40000001 12359.40000039]
[ 3341.50000038  8019.60000001 12361.10000039]
[ 3342.00000038  8020.80000001 12362.80000039]
[ 3342.50000038  8022.00000001 12364.50000039]
[ 3343.00000038  8023.20000001 12366.20000039]
[ 3343.50000038  8024.40000001 12367.90000039]
[ 3344.00000038  8025.60000001 12369.60000039]
[ 3344.50000038  8026.80000001 12371.30000039]
[ 3345.00000038  8028.00000001 12373.00000039]
[ 3345.50000038  8029.20000001 12374.70000039]
[ 3346.00000038  8030.40000001 12376.40000039]
[ 3346.50000038  8031.60000001 12378.10000039]
[ 3347.00000038  8032.80000001 12379.80000039]
[ 3347.500000

[ 3511.50000038  8427.60000001 12939.10000039]
[ 3512.00000038  8428.80000001 12940.80000039]
[ 3512.50000038  8430.00000001 12942.50000039]
[ 3513.00000038  8431.20000001 12944.20000039]
[ 3513.50000038  8432.40000001 12945.90000039]
[ 3514.00000038  8433.60000001 12947.60000039]
[ 3514.50000038  8434.80000001 12949.30000039]
[ 3515.00000038  8436.00000001 12951.00000039]
[ 3515.50000038  8437.20000001 12952.70000039]
[ 3516.00000038  8438.40000001 12954.40000039]
[ 3516.50000038  8439.60000001 12956.10000039]
[ 3517.00000038  8440.80000001 12957.80000039]
[ 3517.50000038  8442.00000001 12959.50000039]
[ 3518.00000038  8443.20000001 12961.20000039]
[ 3518.50000038  8444.40000001 12962.90000039]
[ 3519.00000038  8445.60000001 12964.60000039]
[ 3519.50000038  8446.80000001 12966.30000039]
[ 3520.00000038  8448.00000001 12968.00000039]
[ 3520.50000038  8449.20000001 12969.70000039]
[ 3521.00000038  8450.40000001 12971.40000039]
[ 3521.50000038  8451.60000001 12973.10000039]
[ 3522.000000

[ 3691.00000038  8858.40000002 13549.40000039]
[ 3691.50000038  8859.60000002 13551.10000039]
[ 3692.00000038  8860.80000002 13552.80000039]
[ 3692.50000038  8862.00000002 13554.50000039]
[ 3693.00000038  8863.20000002 13556.20000039]
[ 3693.50000038  8864.40000002 13557.90000039]
[ 3694.00000038  8865.60000002 13559.60000039]
[ 3694.50000038  8866.80000002 13561.30000039]
[ 3695.00000038  8868.00000002 13563.00000039]
[ 3695.50000038  8869.20000002 13564.70000039]
[ 3696.00000038  8870.40000002 13566.40000039]
[ 3696.50000038  8871.60000002 13568.10000039]
[ 3697.00000038  8872.80000002 13569.80000039]
[ 3697.50000038  8874.00000002 13571.50000039]
[ 3698.00000038  8875.20000002 13573.20000039]
[ 3698.50000038  8876.40000002 13574.90000039]
[ 3699.00000038  8877.60000002 13576.60000039]
[ 3699.50000038  8878.80000002 13578.30000039]
[ 3700.00000038  8880.00000002 13580.00000039]
[ 3700.50000038  8881.20000002 13581.70000039]
[ 3701.00000038  8882.40000002 13583.40000039]
[ 3701.500000

[ 3848.50000038  9236.40000002 14084.90000039]
[ 3849.00000038  9237.60000002 14086.60000039]
[ 3849.50000038  9238.80000002 14088.30000039]
[ 3850.00000038  9240.00000002 14090.00000039]
[ 3850.50000038  9241.20000002 14091.70000039]
[ 3851.00000038  9242.40000002 14093.40000039]
[ 3851.50000038  9243.60000002 14095.10000039]
[ 3852.00000038  9244.80000002 14096.80000039]
[ 3852.50000038  9246.00000002 14098.50000039]
[ 3853.00000038  9247.20000002 14100.20000039]
[ 3853.50000038  9248.40000002 14101.90000039]
[ 3854.00000038  9249.60000002 14103.60000039]
[ 3854.50000038  9250.80000002 14105.30000039]
[ 3855.00000038  9252.00000002 14107.00000039]
[ 3855.50000038  9253.20000002 14108.70000039]
[ 3856.00000038  9254.40000002 14110.40000039]
[ 3856.50000038  9255.60000002 14112.10000039]
[ 3857.00000038  9256.80000002 14113.80000039]
[ 3857.50000038  9258.00000002 14115.50000039]
[ 3858.00000038  9259.20000002 14117.20000039]
[ 3858.50000038  9260.40000002 14118.90000039]
[ 3859.000000

[ 3974.50000038  9538.80000002 14513.30000039]
[ 3975.00000038  9540.00000002 14515.00000039]
[ 3975.50000038  9541.20000002 14516.70000039]
[ 3976.00000038  9542.40000002 14518.40000039]
[ 3976.50000038  9543.60000002 14520.10000039]
[ 3977.00000038  9544.80000002 14521.80000039]
[ 3977.50000038  9546.00000002 14523.50000039]
[ 3978.00000038  9547.20000002 14525.20000039]
[ 3978.50000038  9548.40000002 14526.90000039]
[ 3979.00000038  9549.60000002 14528.60000039]
[ 3979.50000038  9550.80000002 14530.30000039]
[ 3980.00000038  9552.00000002 14532.00000039]
[ 3980.50000038  9553.20000002 14533.70000039]
[ 3981.00000038  9554.40000002 14535.40000039]
[ 3981.50000038  9555.60000002 14537.10000039]
[ 3982.00000038  9556.80000002 14538.80000039]
[ 3982.50000038  9558.00000002 14540.50000039]
[ 3983.00000038  9559.20000002 14542.20000039]
[ 3983.50000038  9560.40000002 14543.90000039]
[ 3984.00000038  9561.60000002 14545.60000039]
[ 3984.50000038  9562.80000002 14547.30000039]
[ 3985.000000

[ 4169.50000038 10006.80000002 15176.30000039]
[ 4170.00000038 10008.00000002 15178.00000039]
[ 4170.50000038 10009.20000002 15179.70000039]
[ 4171.00000038 10010.40000002 15181.40000039]
[ 4171.50000038 10011.60000002 15183.10000039]
[ 4172.00000038 10012.80000002 15184.80000039]
[ 4172.50000038 10014.00000002 15186.50000039]
[ 4173.00000038 10015.20000002 15188.20000039]
[ 4173.50000038 10016.40000002 15189.90000039]
[ 4174.00000038 10017.60000002 15191.60000039]
[ 4174.50000038 10018.80000002 15193.30000039]
[ 4175.00000038 10020.00000002 15195.00000039]
[ 4175.50000038 10021.20000002 15196.70000039]
[ 4176.00000038 10022.40000002 15198.40000039]
[ 4176.50000038 10023.60000002 15200.10000039]
[ 4177.00000038 10024.80000002 15201.80000039]
[ 4177.50000038 10026.00000002 15203.50000039]
[ 4178.00000038 10027.20000002 15205.20000039]
[ 4178.50000038 10028.40000002 15206.90000039]
[ 4179.00000038 10029.60000002 15208.60000039]
[ 4179.50000038 10030.80000002 15210.30000039]
[ 4180.000000

[ 4326.00000038 10382.40000002 15708.4000004 ]
[ 4326.50000038 10383.60000002 15710.1000004 ]
[ 4327.00000038 10384.80000002 15711.8000004 ]
[ 4327.50000038 10386.00000002 15713.5000004 ]
[ 4328.00000038 10387.20000002 15715.2000004 ]
[ 4328.50000038 10388.40000002 15716.9000004 ]
[ 4329.00000038 10389.60000002 15718.6000004 ]
[ 4329.50000038 10390.80000002 15720.3000004 ]
[ 4330.00000038 10392.00000002 15722.0000004 ]
[ 4330.50000038 10393.20000002 15723.7000004 ]
[ 4331.00000038 10394.40000002 15725.4000004 ]
[ 4331.50000038 10395.60000002 15727.1000004 ]
[ 4332.00000038 10396.80000002 15728.8000004 ]
[ 4332.50000038 10398.00000002 15730.5000004 ]
[ 4333.00000038 10399.20000002 15732.2000004 ]
[ 4333.50000038 10400.40000002 15733.9000004 ]
[ 4334.00000038 10401.60000002 15735.6000004 ]
[ 4334.50000038 10402.80000002 15737.3000004 ]
[ 4335.00000038 10404.00000002 15739.0000004 ]
[ 4335.50000038 10405.20000002 15740.7000004 ]
[ 4336.00000038 10406.40000002 15742.4000004 ]
[ 4336.500000

[ 4431.00000038 10634.40000002 16065.4000004 ]
[ 4431.50000038 10635.60000002 16067.1000004 ]
[ 4432.00000038 10636.80000002 16068.8000004 ]
[ 4432.50000038 10638.00000002 16070.5000004 ]
[ 4433.00000038 10639.20000002 16072.2000004 ]
[ 4433.50000038 10640.40000002 16073.9000004 ]
[ 4434.00000038 10641.60000002 16075.6000004 ]
[ 4434.50000038 10642.80000002 16077.3000004 ]
[ 4435.00000038 10644.00000002 16079.0000004 ]
[ 4435.50000038 10645.20000002 16080.7000004 ]
[ 4436.00000038 10646.40000002 16082.4000004 ]
[ 4436.50000038 10647.60000002 16084.1000004 ]
[ 4437.00000038 10648.80000002 16085.8000004 ]
[ 4437.50000038 10650.00000002 16087.5000004 ]
[ 4438.00000038 10651.20000002 16089.2000004 ]
[ 4438.50000038 10652.40000002 16090.9000004 ]
[ 4439.00000038 10653.60000002 16092.6000004 ]
[ 4439.50000038 10654.80000002 16094.3000004 ]
[ 4440.00000038 10656.00000002 16096.0000004 ]
[ 4440.50000038 10657.20000002 16097.7000004 ]
[ 4441.00000038 10658.40000002 16099.4000004 ]
[ 4441.500000

[ 4552.00000038 10924.80000002 16476.8000004 ]
[ 4552.50000038 10926.00000002 16478.5000004 ]
[ 4553.00000038 10927.20000002 16480.2000004 ]
[ 4553.50000038 10928.40000002 16481.9000004 ]
[ 4554.00000038 10929.60000002 16483.6000004 ]
[ 4554.50000038 10930.80000002 16485.3000004 ]
[ 4555.00000038 10932.00000002 16487.0000004 ]
[ 4555.50000038 10933.20000002 16488.7000004 ]
[ 4556.00000038 10934.40000002 16490.4000004 ]
[ 4556.50000038 10935.60000002 16492.1000004 ]
[ 4557.00000038 10936.80000002 16493.8000004 ]
[ 4557.50000038 10938.00000002 16495.5000004 ]
[ 4558.00000038 10939.20000002 16497.2000004 ]
[ 4558.50000038 10940.40000002 16498.9000004 ]
[ 4559.00000038 10941.60000002 16500.6000004 ]
[ 4559.50000038 10942.80000002 16502.3000004 ]
[ 4560.00000038 10944.00000002 16504.0000004 ]
[ 4560.50000038 10945.20000002 16505.7000004 ]
[ 4561.00000038 10946.40000002 16507.4000004 ]
[ 4561.50000038 10947.60000002 16509.1000004 ]
[ 4562.00000038 10948.80000002 16510.8000004 ]
[ 4562.500000

[ 4672.00000038 11212.80000002 16884.8000004 ]
[ 4672.50000038 11214.00000002 16886.5000004 ]
[ 4673.00000038 11215.20000002 16888.2000004 ]
[ 4673.50000038 11216.40000002 16889.9000004 ]
[ 4674.00000038 11217.60000002 16891.6000004 ]
[ 4674.50000038 11218.80000002 16893.3000004 ]
[ 4675.00000038 11220.00000002 16895.0000004 ]
[ 4675.50000038 11221.20000002 16896.7000004 ]
[ 4676.00000038 11222.40000002 16898.4000004 ]
[ 4676.50000038 11223.60000002 16900.1000004 ]
[ 4677.00000038 11224.80000002 16901.8000004 ]
[ 4677.50000038 11226.00000002 16903.5000004 ]
[ 4678.00000038 11227.20000002 16905.2000004 ]
[ 4678.50000038 11228.40000002 16906.9000004 ]
[ 4679.00000038 11229.60000002 16908.6000004 ]
[ 4679.50000038 11230.80000002 16910.3000004 ]
[ 4680.00000038 11232.00000002 16912.0000004 ]
[ 4680.50000038 11233.20000002 16913.7000004 ]
[ 4681.00000038 11234.40000002 16915.4000004 ]
[ 4681.50000038 11235.60000002 16917.1000004 ]
[ 4682.00000038 11236.80000002 16918.8000004 ]
[ 4682.500000

[ 4895.50000038 11749.20000002 17644.7000004 ]
[ 4896.00000038 11750.40000002 17646.4000004 ]
[ 4896.50000038 11751.60000002 17648.1000004 ]
[ 4897.00000038 11752.80000002 17649.8000004 ]
[ 4897.50000038 11754.00000002 17651.5000004 ]
[ 4898.00000038 11755.20000002 17653.2000004 ]
[ 4898.50000038 11756.40000002 17654.9000004 ]
[ 4899.00000038 11757.60000002 17656.6000004 ]
[ 4899.50000038 11758.80000002 17658.3000004 ]
[ 4900.00000038 11760.00000002 17660.0000004 ]
[ 4900.50000038 11761.20000002 17661.7000004 ]
[ 4901.00000038 11762.40000002 17663.4000004 ]
[ 4901.50000038 11763.60000002 17665.1000004 ]
[ 4902.00000038 11764.80000002 17666.8000004 ]
[ 4902.50000038 11766.00000002 17668.5000004 ]
[ 4903.00000038 11767.20000002 17670.2000004 ]
[ 4903.50000038 11768.40000002 17671.9000004 ]
[ 4904.00000038 11769.60000002 17673.6000004 ]
[ 4904.50000038 11770.80000002 17675.3000004 ]
[ 4905.00000038 11772.00000002 17677.0000004 ]
[ 4905.50000038 11773.20000002 17678.7000004 ]
[ 4906.000000

array([ 5000.00000038, 12000.00000002, 18000.0000004 ])

In [171]:
def gradient_descent1(y, X, w0, gamma, max_iters):
    w=w0
    for n in range(max_iters):
        grad = compute_gradient(y,X,w)
        #print(grad)
        w = w - gamma*grad
        #print(w)
    return w

y=np.array([1,0,1,7])
X=np.array([[9,0,11],[1,0,1],[1,0,1],[1,2,3]])
w0=np.array([0,90,0])
#y=np.array([1,0,1])
#X=np.array([[9,0,11],[1,0,1],[1,0,1]])
#w0=np.array([-1,1,1])
max_iters=1000
gamma=0.1
gradient_descent1(y, X, w0, gamma, max_iters)
compute_gradient(y,X,w0)

array([-10.,   0., -12.])

In [105]:
def logistic_regression(y, tx, initial_w, max_iters, gamma):
    w=gradient_descent(y, tx, initial_w, gamma, max_iters)
    S=0
    for n in range(tx.shape[0]):
        z=np.dot(tx[n,:],w)
        z=pow(z,2.718281828459045)
        z=np.log(1+z)
        m=y[n]*np.dot(tx[n,:],w)
        print(z)
        print(m)
        S+= z-m
    return (w,S)        

### Test

In [124]:
y=np.array([1,0,1])
tx=np.array([[9,0,11],[1,0,1],[1,0,1]])
initial_w=np.array([-1,0,2])
max_iters=1000
gamma=0.1

logistic_regression(y, tx, initial_w, max_iters, gamma)


7.02434801244219
13.247193017189197
0.7020951594542215
0.0
0.7020951594542215
1.0065758880582614


(array([-1.08742912,  0.        ,  2.09400501]), -5.8252305738968255)